apiVersion: v1
kind: Service
metadata:
  name: trend-webapp-service
spec:
  type: LoadBalancer
  selector:
    app: trend-webapp
  ports:
    - protocol: TCP
      port: 3000        # external port (standard web traffic)
      targetPort: 3000  # container port (your app)